format_version: v1.0
type: UniqueComponent
attributes: {id: ip1553}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: IP1553_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ip1553, value: '12000000'}
  - type: KeyValueSet
    attributes: {id: IP1553_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ip1553, value: '1'}
  - type: Integer
    attributes: {id: IP1553_RT_ADDR}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '312', y: '76', id: ip1553}
