package:
  format-version: "1.0.0"
  name: "aerospace_apps_sam_rh71"
  version: "v3.1.0"
  type: "application"
  status: "production"
  required: true

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.18.0"
    - name: "aerospace"
      type: "package"
      version: "v3.4.0"
    - name: "dev_packs"
      type: "package"
      version: "3.18.0"
