format_version: v1.0
type: UniqueComponent
attributes: {id: rtc}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: RTC_MR_OUT0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: FREQ32HZ}
  - type: Combo
    attributes: {id: RTC_MR_OUT1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: PROG_PULSE}
  - type: Combo
    attributes: {id: RTC_MR_THIGH}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: RTC_MR_TPERIOD}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '25', y: '141', id: rtc}
