format_version: v1.0
type: UniqueComponent
attributes: {id: ip1553}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: IP1553_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ip1553, value: '12000000'}
  - type: KeyValueSet
    attributes: {id: IP1553_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ip1553, value: '1'}
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: IP1553_RT_ADDR}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '310', y: '72', id: ip1553}
