format_version: v1.0
type: UniqueComponent
attributes: {id: icm}
children:
- type: Symbols
  children:
  - type: Menu
    attributes: {id: ICM_REGION_DESC0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ICM_REGION_DESC0_ALGO}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '0'}
  - type: KeyValueSet
    attributes: {id: ICM_REGION_DESC0_CDWBN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '0'}
  - type: KeyValueSet
    attributes: {id: ICM_REGION_DESC0_PROCDLY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '0'}
  - type: Integer
    attributes: {id: ICM_REGION_DESC0_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10048'}
  - type: Integer
    attributes: {id: ICM_REGION_DESC0_SIZE_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '156'}
  - type: Hex
    attributes: {id: ICM_REGION_DESC0_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '65536'}
  - type: Menu
    attributes: {id: ICM_REGION_DESC1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ICM_REGION_DESC1_ALGO}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '0'}
  - type: KeyValueSet
    attributes: {id: ICM_REGION_DESC1_CDWBN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '0'}
  - type: KeyValueSet
    attributes: {id: ICM_REGION_DESC1_PROCDLY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '0'}
  - type: Integer
    attributes: {id: ICM_REGION_DESC1_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10048'}
  - type: Integer
    attributes: {id: ICM_REGION_DESC1_SIZE_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '156'}
  - type: Hex
    attributes: {id: ICM_REGION_DESC1_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '536870912'}
  - type: Menu
    attributes: {id: ICM_REGION_DESC2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ICM_REGION_DESC2_ALGO}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '0'}
  - type: KeyValueSet
    attributes: {id: ICM_REGION_DESC2_CDWBN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '0'}
  - type: KeyValueSet
    attributes: {id: ICM_REGION_DESC2_PROCDLY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '0'}
  - type: Integer
    attributes: {id: ICM_REGION_DESC2_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10048'}
  - type: Integer
    attributes: {id: ICM_REGION_DESC2_SIZE_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '156'}
  - type: Hex
    attributes: {id: ICM_REGION_DESC2_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '554369024'}
  - type: Menu
    attributes: {id: ICM_REGION_DESC3}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ICM_REGION_DESC3_ALGO}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '0'}
  - type: KeyValueSet
    attributes: {id: ICM_REGION_DESC3_CDWBN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '0'}
  - type: KeyValueSet
    attributes: {id: ICM_REGION_DESC3_PROCDLY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '0'}
  - type: Integer
    attributes: {id: ICM_REGION_DESC3_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10048'}
  - type: Integer
    attributes: {id: ICM_REGION_DESC3_SIZE_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icm, value: '156'}
  - type: Hex
    attributes: {id: ICM_REGION_DESC3_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1677721600'}
  - type: Boolean
    attributes: {id: ICM_REGION_DESC3_WRAP}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: REGION_DESC_NUM}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
  - type: Boolean
    attributes: {id: SLBDIS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '25', y: '159', id: icm}
