format_version: v1.0
type: UniqueComponent
attributes: {id: tcmecc}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: INJECTION_TEST_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '170', y: '159', id: tcmecc}
